// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkEED0rTiHyEJDb_0Kxt1EBdGvRnBxCG4',
    appId: '1:755135612755:web:b7d3cfd0e592504aac43a6',
    messagingSenderId: '755135612755',
    projectId: 'cosport-debd8',
    authDomain: 'cosport-debd8.firebaseapp.com',
    databaseURL: 'https://cosport-debd8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosport-debd8.appspot.com',
    measurementId: 'G-JGTZM7EQRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAojfmyUePkUayENo0jPX9NO6BonP6rtwU',
    appId: '1:755135612755:android:dc3a4c02920a0d53ac43a6',
    messagingSenderId: '755135612755',
    projectId: 'cosport-debd8',
    databaseURL: 'https://cosport-debd8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosport-debd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQsvDajo19WXkaplt_OoJ77Nky2Pgtxds',
    appId: '1:755135612755:ios:09a3fa1672d6b760ac43a6',
    messagingSenderId: '755135612755',
    projectId: 'cosport-debd8',
    databaseURL: 'https://cosport-debd8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosport-debd8.appspot.com',
    androidClientId: '755135612755-agktd52jsbamn8a136gkrkg6t77qkfi3.apps.googleusercontent.com',
    iosClientId: '755135612755-tks4ceo812g3b1l0oo38viip9o0453rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.coSportMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQsvDajo19WXkaplt_OoJ77Nky2Pgtxds',
    appId: '1:755135612755:ios:09a3fa1672d6b760ac43a6',
    messagingSenderId: '755135612755',
    projectId: 'cosport-debd8',
    databaseURL: 'https://cosport-debd8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'cosport-debd8.appspot.com',
    androidClientId: '755135612755-agktd52jsbamn8a136gkrkg6t77qkfi3.apps.googleusercontent.com',
    iosClientId: '755135612755-tks4ceo812g3b1l0oo38viip9o0453rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.coSportMap',
  );
}
